# -*- ruby -*-

# DO NOT EDIT THIS FILE. Instead, edit Rakefile, and run `rake bundler:gemfile`.

source "https://rubygems.org/"

gem "loofah", ">=1.0.0"

gem "bundler", "~>1.2.0", :group => [:development, :test]
gem "hoe", "~>3.3", :group => [:development, :test]
gem "rr", "~>1.0", :group => [:development, :test]
gem "hoe-gemspec", ">=0", :group => [:development, :test]
gem "rdoc", "~>3.10", :group => [:development, :test]
gem "hoe-git", ">=0", :group => [:development, :test]
gem "hoe-bundler", ">=0", :group => [:development, :test]
gem "minitest", "~>2.2", :group => [:development, :test]
gem "acts_as_fu", ">=0.0.5", :group => [:development, :test]

# vim: syntax=ruby
