#! /usr/bin/env ruby

unless ARGV[0]
  puts "USAGE: #{File.basename($0)} <rails-version> [flavor]"
  puts
  puts " e.g., '#{File.basename($0)} 2.3.4'"
  puts "       '#{File.basename($0)} 2.3.4 ar_scrub'"
  puts
  exit 1
end

version = ARGV[0]
flavor = ARGV[1]

require "rubygems"
require "tmpdir"

def run(cmd)
  puts "* running '#{cmd}'"
  system cmd
  raise "command failed" unless $? == 0
end

def rails version, dir
  thisdir = Dir.pwd
  Dir.mktmpdir do |tmpdir|
    Dir.chdir tmpdir do
      begin
        gem "rails", "=#{version}"
      rescue Gem::LoadError => e
        puts "ERROR: could not find rails version #{version}"
        puts "Try running:"
        puts "  gem install rails --version=#{version}"
        exit 1
      end
      puts "* successfully detected rails version #{version}"
      if version >= "3"
        run "yes | rails _#{version}_ new #{dir} > /dev/null"
      else
        run "yes | rails _#{version}_ #{dir} > /dev/null"
      end
      FileUtils.mv dir, thisdir
    end
  end
end

if flavor
  flavors = [flavor]
else
  flavors = Dir.chdir("common") { Dir["*"] } - ['all']
end

flavors.each do |flavor|
  dir = "rails-#{version}-#{flavor}"
  rails version, dir unless File.exists?(dir)
  run "rsync -a common/all/ #{dir}"
  run "rsync -a common/#{flavor}/ #{dir}"
end
